# manifest to be imported by dependents (if dependency exists)
manifest:
  self:
    import: west/west-dependency/west-dependency.yml
  # Please edit west/west-dependency/west-dependency.yml to change dependencies

